### ISSUE TITLE
Make icons clickable to show shipment info

### ISSUE THREAD

**Issue by coderbyheart** [distributeaid/shipments#2]

**Comment by vipin8169** [comment]
Please provide more information about what needs to be done here. Which icons to be clicked to show what info?

**Comment by coderbyheart** [comment]
![Screenshot_20200419_105058](https://user-images.githubusercontent.com/188915/79683635-afa12680-822b-11ea-888c-290cb378ea0b.png)

The map shows icons for the origin and destination of a shipment.
It would be nice to show more information about the shipment (which is available in the datasource), when the user clicks on the icons (and the line connecting them).

Please feel free to come up with a proposal, we might even be able to include data which is not yet in the data source, if you think this is valuable.

**Comment by vipin8169** [comment]
Does this look good? This pop-up appears on clicking the marker.
![image](https://user-images.githubusercontent.com/4578304/79733077-6a233e80-82a9-11ea-8253-bd7e7e45dd31.png)

However, I am not sure if I should display same info on the origin, destination as well as the line connecting them.

**Comment by coderbyheart** [comment]
> Does this look good? This pop-up appears on clicking the marker.
> ![image](https://user-images.githubusercontent.com/4578304/79733077-6a233e80-82a9-11ea-8253-bd7e7e45dd31.png)

Yes, and please format the numbers, as done in the summary. 

> However, I am not sure if I should display same info on the origin, destination as well as the line connecting them.

What would you propose?

**Comment by vipin8169** [comment]
Is this how you wanted the number formatting to be?
![image](https://user-images.githubusercontent.com/4578304/79737330-03555380-82b0-11ea-9a4e-71dd31a50e9a.png)

**Comment by coderbyheart** [comment]
It should be the same way it is in the summary below.
This is not the case in your screenshot.

**Comment by vipin8169** [comment]
By summary, you mean the part highlighted in red, right? does it look better now?
![image](https://user-images.githubusercontent.com/4578304/79738254-5ed41100-82b1-11ea-91f3-0a7007bf1f2e.png)

**Comment by vipin8169** [comment]
Also, I could add the units for weight, but I do not know what the units are.

**Comment by coderbyheart** [comment]
> By summary, you mean the part highlighted in red, right?

Yes.

> does it look better now?

Yes, please also format the weight accordingly.

> Also, I could add the units for weight, but I do not know what the units are.

They are documented in the [data source](https://docs.google.com/spreadsheets/d/1f5H0sOY4tfkQF_QkQemt1GHTYd_wgsvBgmzE4miI9g4/export?format=tsv): kg for weight, EUR for value.

**Comment by vipin8169** [comment]
I am sorry, I was not aware of that. should i push in the main branch saga?

**Comment by coderbyheart** [comment]
Please create a PR.

**Comment by vipin8169** [comment]
For that I have to create a new branch and push into it, right?

**Comment by coderbyheart** [comment]
Yes, but you can also fork the repo and push to saga there. Whatever works better for you.
