### ISSUE TITLE
Add section for sponsors

### ISSUE THREAD

**Issue by coderbyheart** [distributeaid/shipments#4]
We want to show companies that support the shipments, so we need a section to show sponsors for three different tiers (2-5 for each tier). 
Sponsors should be shown with a logo (SVG), a title and link to their homepages.
The actual sponsors have not yet been finalized, so placeholders should be used for now.

The section (as all components on the page), must be implemented mobile first.

**Comment by vipin8169** [comment]
I can pick this up, but need more information to work on it.

**Comment by coderbyheart** [comment]
What information are you missing?

**Comment by vipin8169** [comment]
The shipments shown on the homepage, they are past ones, right?
where do i get the current shipments? how many sponsors are there? where do i show them on page, how will the page look like? should sponsors be a part of footer?

**Comment by coderbyheart** [comment]
> The shipments shown on the homepage, they are past ones, right?

No, they are past and current shipments.

> where do i get the current shipments? 

From the same datasource, they will eventually be entered there.

> how many sponsors are there?

This is described above.

> where do i show them on page, how will the page look like?

This needs to be designed and is part of the scope of this issue.

> should sponsors be a part of footer?

I understand that the sponsors would then appear twice on the page. Why do you think this is valuable for the user?

**Comment by vipin8169** [comment]
Ah, I can develop not design :(

**Comment by coderbyheart** [comment]
This will be implemented in the landing page project: https://gitlab.com/distribute-aid/landing
